// AUTO-GENERATED by scripts/build-tajweed-font.mjs — do not edit by hand.
// Maps tajweed rule id → PUA codepoint inside tajweed-symbols.woff2.
export const TAJWEED_CHAR_GENERATED: Record<number, string> = {
  1: "\uE001",
  2: "\uE002",
  3: "\uE003",
  4: "\uE004",
  5: "\uE005",
  6: "\uE006",
  7: "\uE007",
  8: "\uE008",
  9: "\uE009",
  10: "\uE00A",
  11: "\uE00B",
  12: "\uE00C",
};
